// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef BRAND_ODB_HXX
#define BRAND_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "brand.h"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // brand
  //
  template <>
  struct class_traits< ::brand >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::brand >
  {
    public:
    typedef ::brand object_type;
    typedef ::brand* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // brand
  //
  template <typename A>
  struct query_columns< ::brand, id_mysql, A >
  {
    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    id_type_;

    static const id_type_ id;

    // name
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    name_type_;

    static const name_type_ name;

    // img_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long int,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    img_id_type_;

    static const img_id_type_ img_id;

    // is_recommended
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    is_recommended_type_;

    static const is_recommended_type_ is_recommended;

    // upload_type_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long int,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    upload_type_id_type_;

    static const upload_type_id_type_ upload_type_id;

    // info
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    info_type_;

    static const info_type_ info;
  };

  template <typename A>
  const typename query_columns< ::brand, id_mysql, A >::id_type_
  query_columns< ::brand, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename query_columns< ::brand, id_mysql, A >::name_type_
  query_columns< ::brand, id_mysql, A >::
  name (A::table_name, "`name`", 0);

  template <typename A>
  const typename query_columns< ::brand, id_mysql, A >::img_id_type_
  query_columns< ::brand, id_mysql, A >::
  img_id (A::table_name, "`img_id`", 0);

  template <typename A>
  const typename query_columns< ::brand, id_mysql, A >::is_recommended_type_
  query_columns< ::brand, id_mysql, A >::
  is_recommended (A::table_name, "`is_recommended`", 0);

  template <typename A>
  const typename query_columns< ::brand, id_mysql, A >::upload_type_id_type_
  query_columns< ::brand, id_mysql, A >::
  upload_type_id (A::table_name, "`upload_type_id`", 0);

  template <typename A>
  const typename query_columns< ::brand, id_mysql, A >::info_type_
  query_columns< ::brand, id_mysql, A >::
  info (A::table_name, "`info`", 0);

  template <typename A>
  struct pointer_query_columns< ::brand, id_mysql, A >:
    query_columns< ::brand, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::brand, id_mysql >:
    public access::object_traits< ::brand >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      unsigned long long id_value;
      my_bool id_null;

      // name_
      //
      details::buffer name_value;
      unsigned long name_size;
      my_bool name_null;

      // img_id_
      //
      long long img_id_value;
      my_bool img_id_null;

      // is_recommended_
      //
      int is_recommended_value;
      my_bool is_recommended_null;

      // upload_type_id
      //
      long long upload_type_id_value;
      my_bool upload_type_id_null;

      // info_
      //
      details::buffer info_value;
      unsigned long info_size;
      my_bool info_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 6UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::brand, id_common >:
    public access::object_traits_impl< ::brand, id_mysql >
  {
  };

  // brand
  //
}

#include "brand-odb.ixx"

#include <odb/post.hxx>

#endif // BRAND_ODB_HXX
